name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            outfile: devm8-macos-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            outfile: devm8-macos-x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            outfile: devm8-linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      - run: cargo build --release --target=${{ matrix.target }}
      - run: cp target/${{ matrix.target }}/release/devm8 ${{ matrix.outfile }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.outfile }}
          path: ${{ matrix.outfile }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/
      - run: cd artifacts && sha256sum * > ../checksums.txt
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: |
            artifacts/*
            checksums.txt
